### PR TITLE
Removed warnings that come up from byte compiling.

### PR DESCRIPTION
**Pull request by zenspider**
This doesn't deal with lexical-let + cl.

### CODE REVIEW

**Comment by zenspider** [comment]
@gcv I just rebased against latest master and got a new one... Does this seem reasonable?

```diff
-                (state-complete (read-from-whole-string
-                                 (with-temp-buffer
-                                   (insert-file-contents file)
-                                   (buffer-string)))))
+                (state-complete (with-temp-buffer
+                                  (insert-file-contents-literally path)
+                                  (buffer-string))))
```

I don't understand the use of `read-from-whole-string` (now `thing-at-point--read-from-whole-string`) in this context... So my change might not cover what you want.

**Comment by gcv** [comment]
The intent is to call `read` on the persisted state file. I switched `read-from-whole-string` because it flags an error if there's more stuff left after a successful `read` call. The difference in behavior between `(read "(list 1 2) (list 3 4)")` and `(read-from-whole-string "(list 1 2) (list 3 4)")` is that the first just returns `(1 2)` and the second errors out. This was helpful in flagging situations when `persp-state-save` just appended state to an existing file instead of overwriting it (or prompting).

There should now be adequate logic to prevent that from happening, and I haven't seen this error pop up in many months. The choices are:

1. Switch to using `thing-at-point--read-from-whole-string`.
2. Copy the implementation of `thing-at-point--read-from-whole-string` into perspective.
3. Switch to vanilla `read` and hope all the overwriting logic works.

**Comment by zenspider** [comment]
I went with `thing-at-point--read-from-whole-string` in the end, but I think I'd prefer `read` since the file format is just one sexp.

**Comment by zenspider** [comment]
I got it fixed up for 24.4. We can switch to read in a separate PR. I think these two PRs can go in. I'll file an issue for the switch.

**Pull request merged**
