### PR TITLE
Support perspective wrapping on `persp-next` and `persp-prev`

### PR DESCRIPTION
**Pull request by redshirtrob**
Add customization point `persp-switch-wrap` to enable wrapping

### CODE REVIEW

**Comment by nex3** [comment]
I'd be fine with this defaulting to `t`.

**Comment by redshirtrob** [comment]
Same here, but I did not want to be presumptuous. :)  

I will fold that change in and update the PR.  Do you prefer that I squash the changes down to one commit?

**Comment by nex3** [comment]
Yeah, that would be nice.

**Comment by redshirtrob** [comment]
The PR is updated.

**Comment by redshirtrob** [comment]
@nex3 I made the suggested change and updated the PR.

**Pull request merged**
