### PR TITLE
Attempt to switch to lexical scope

### PR DESCRIPTION
**Pull request by zenspider**

### CODE REVIEW

**Comment by zenspider** [comment]
I just put in a fix for 24.4 which didn't have the `thing-at-pt` function so I aliased it. The test was an easy conversion. Looks like this might be good to go?

**Comment by zenspider** [comment]
I've been working with these for a week now w/o problems... I'm gonna merge both in to master (probably locally to avoid PR on PR issues I've had in the past)

**Comment by gcv** [comment]
Should we delete the merged branches `lexical-scope` and `byte-compile-cleanup`?

**Comment by zenspider** [comment]
I usually delete remotely via `git remote update --prune`.

**Pull request merged**
