### PR TITLE
fix scratch buffer creation, fix current-buffer not updated, fix pulling buffer from other perspective, fix/add ert tests

### PR DESCRIPTION
**Pull request by mehw**
Hello,

This serie of patches is my effort to fix different things and add more ERT tests... By the way, I have more in my stash, I just need time for debug and to design ERT tests... there's more to come...

This possibly also addresses issue #164, by fixing the update of the `current-buffer` when switching perspective and removing buffers, and by preventig the killing/removal of a perspective's last left buffer (more in the summary below).

About Emacs, I already assigned the copyright to the FSF...

### Scratch Buffer

- `persp-new`: `initial-scratch-message` command keys should be substituted to command names when the message is inserted into a scratch buffer:
  `;; This buffer is for text that is not saved, and for Lisp evaluation.`
  `;; To create a file, visit it with \\[find-file] and enter text in its buffer.`
- `persp-get-scratch-buffer`: new utility function to get/create a perspective's scratch buffer.  Adapt `persp-new` and `persp-other-buffer` to use this function.
- `persp-switch-to-scratch-buffer`: interactive function to get/create a perspective's scratch buffer.  Bind to `C-x x B` for ease of use.

*New ERT tests*

- `basic-persp-get-scratch-buffer`: test scratch buffers conformity and creation, also evaluate `persp-get-scratch-buffer`.
- `basic-persp-switch-to-scratch-buffer`: evaluate `persp-switch-to-scratch-buffer`.

### Update `current-buffer`

- `make-persp`: add comments about saving/restoring the `current-buffer` when executing `BODY`.
- `persp-activate`: `make-persp` saves/restores the `current-buffer` when executing `BODY`, hence when the current buffer is changed, a forced update of `current-buffer` is required.
- `persp-remove-buffer`: `with-selected-window` saves/restores the `current-buffer` when executing `BODY`, hence when the current buffer is changed, a forced update of `current-buffer` is required.

*Changed ERT tests*

- `basic-persp-switching`: tests the `current-buffer` too.

### Keep a perspective's last left buffer alive

- `persp-maybe-kill-buffer`: new hook for `kill-buffer-query-functions` to prevent a perspective's last buffer from being killed.  Adapt `persp-mode`, `persp-kill`, `persp-set-buffer`, and `persp-remove-buffer` to use this new feature.
- `persp-remove-buffer`: do not remove a perspective's last left buffer.
- `persp-forget-buffer`: (new utility function) do not disassociate a perspective's last left buffer.

*New ERT tests*

- `basic-persp-killing-buffers`: test killing buffers, a perspective's last left live buffer should not be killable/removable.

### Prevent resetting a perspective state

- `persp-new`: do not reset a perspective to a state where there's only the perspective's scratch buffer in it.
- `persp-switch`: use the fixed `persp-new` to get an existing perspective, hence remove duplicated code.

### Miscellaneous fixes/changes

- `persp-reset-windows`: set `switch-to-buffer-preserve-window-point` to `nil`, in order to not update `windows-prev-buffers`.
- `persp-add-buffer`: discard a non-existent buffer given as argument.
- `persp-set-buffer`: follow the coding style of `persp-add-buffer`.

*New ERT tests*

- `basic-persp-window-prev-buffers`: evaluate if `windows-prev-buffers` gets buffers from other perspectives.
- `basic-persp-add-buffer`: evaluate `persp-add-buffer`.
- `basic-persp-set-buffer`: evaluate `persp-set-buffer`.

### New utility functions

- `persp-get-buffers`: (introduced to simplify some ERT tests) return all the buffers of a specific perspective given as argument that may be found in the specified frame (if given), or in the current frame.
- `persp-get-buffer-names`: (introduced to simplify some ERT tests) return the live buffers of a specific perspective given as argument that may be found in the specified frame (if given), or in the current frame.
- `persp-forget-buffer`: balances `persp-add-buffer`.  Disassociate a buffer from a perspective without killing it.  Make use of this function in `persp-remove-buffer`, `persp-set-buffer`, and `persp-maybe-kill-buffer`.

*New ERT tests*

- `basic-persp-get-buffers`: evaluate `persp-get-buffers`.
- `basic-persp-get-buffer-names`: evaluate `persp-get-buffer-names`.
- `basic-persp-forget-buffer`: evaluate `persp-forget-buffer`.

### Fixed ERT functions/macros

- `persp-test-with-persp`: verify that a `*scratch* (NAME)` buffer exists before killing it; kill other perspectives than the main perspective when cleaning up; `unwind-protect` BODY to ensure a proper cleanup upon failures.

*New ERT tests*

- `basic-persp-test-with-persp`: evaluate `persp-test-with-persp` macro.

### Changed ERT tests

- `basic-persp-creation-deletion`: test killing all perspectives, main perspective included.

### New ERT utility functions

- `persp-test-match-scratch-buffers`: list live buffers that may all be considered scratch buffers.  Also, alllows to verify that the buffers found are just the ones given as arguments.
- `persp-test-kill-extra-buffers`: automatically kill scratch buffers that are not the `*scratch*` buffer.  Also, allows to kill extra buffers given as arguments.
- `persp-test-buffer-in-persps`: verify that a buffer is in specified perspectives only, or in no perspective at all if no argument is given.

*New ERT tests*

- `basic-persp-test-match-scratch-buffers`: evaluate `persp-test-match-scratch-buffers`.
- `baisc-persp-test-kill-extra-buffers`: evaluate `persp-test-kill-extra-buffers`
- `basic-persp-test-buffer-in-persps`: evaluate `persp-test-buffer-in-persps`.

### CODE REVIEW

**Comment by gcv** [comment]
That's a big but promising-looking PR. Thanks for doing all this work. Since some tests are currently failing, I assume it's still a work in progress. Please let me know when you're ready for me to review it in detail.

**Comment by mehw** [comment]
> That's a big but promising-looking PR. Thanks for doing all this work. Since some tests are currently failing, I assume it's still a work in progress. Please let me know when you're ready for me to review it in detail.

Strangely, if I run the tests interactively, they all pass...

It's just `emacs -nw -Q -batch -L . -l ert -l test/test-perspective.el --eval "(ert-run-tests-batch-and-exit)"` that gives me troubles...

By the way, I started looking into it... I'll post an update/amend as soon as possible.

Thank you @gcv.

**Comment by mehw** [comment]
I can see the problem about the failures now...

First of all, I was using Emacs git 7e8d1b08e3e23bc783cad10e620c2ebe6536965c, hence running non-interactive tests reported only the error about `basic-persp-creation-deletion`. After switching to Emacs 27.2 errors about `basic-persp-forget-buffer` and `basic-persp-killing-buffers` are also reported, and this time even when running the tests interactively.

Currently, I resolved the error about `basic-persp-creation-deletion`, and I'm investigating `basic-persp-forget-buffer` and `basic-persp-killing-buffers` errors...

**Comment by gcv** [comment]
Emacs 28 has different test outcomes from 27.2? Do you know what changed?

**Comment by mehw** [comment]
I need to check and compare the code. Right now I'm debugging the failures about `basic-persp-forget-buffer` and `basic-persp-killing-buffers` tests, but I hope to eventually get there.

**Comment by gcv** [comment]
@mehw: Thanks for investigating this. I’m looking forward to merging in your patch.

**Comment by mehw** [comment]
Hi @gcv, hopefully everything should work now.

Till Emacs 27.2, `delete-window` requires `switch-to-buffer-preserve-window-point` set to `nil` to keep an empty `window-prev-buffers` when calling `persp-reset-windows`.

Upstream commit 8f63f0078a23421eada97b4da51b9308b82532ce reverted window/winner changes (Revert 0454bfd3313) in Emacs (bug#23621), removing `switch-to-buffer-preserve-window-point` from `delete-window`.  From that commit on, with default settings, `delete-window` seems to not update `windows-prev-buffers` of all windows automatically any more (which is what we may achieve before that commit with `switch-to-buffer-preserve-window-point` set to `nil`).

I had to modify `basic-persp-get-scratch-buffer` to accomodate for an `initial-scratch-messagge` in plain text before Emacs 25.1.

Pseudo code:

```
(setq default-scratch-message (substitute-command-keys initial-scratch-message))
(if (or (> emacs-major-version 25)
        (and (= emacs-major-version 25) (>= emacs-minor-version 1)))
    ;; Treat `initial-scratch-message' as a doc string.
    (should-not (equal initial-scratch-message default-scratch-message))
  ;; Treat `initial-scratch-message' as plain text.
  (should (equal initial-scratch-message default-scratch-message)))
```

**Pull request merged**
